# Generated by Django 5.2.6 on 2025-09-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
