# Generated by Django 5.2.6 on 2025-09-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_demorequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features/image')),
                ('icon', models.ImageField(upload_to='features/icon')),
                ('icon_background', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('testimonial_description', models.TextField()),
                ('testimonial_author', models.CharField(max_length=128)),
                ('author_designation', models.CharField(max_length=128)),
                ('testimonial_logo', models.ImageField(upload_to='features/logo')),
            ],
        ),
    ]
