# Generated by Django 5.2.6 on 2025-09-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_features_icon_alter_features_testimonial_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/image')),
                ('blog_type', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('link', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='midFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='midfeatures/image')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='products/logo')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/image')),
                ('bg_color', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/image')),
                ('testimonial_logo', models.FileField(upload_to='reviews/logo')),
                ('title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='testimonials/image')),
                ('testimonial_logo', models.FileField(upload_to='testimonials/logo')),
                ('title', models.CharField(max_length=128)),
                ('testimonial_name', models.CharField(max_length=128)),
                ('author_job', models.CharField(max_length=128)),
                ('author_designation', models.CharField(max_length=128)),
            ],
        ),
    ]
