# Generated by Django 5.2.6 on 2025-09-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_blog_midfeatures_products_reviews_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='link',
            field=models.CharField(default='#', max_length=128),
        ),
    ]
