# Generated by Django 5.2.6 on 2025-09-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='decription',
            new_name='description',
        ),
    ]
