# Generated by Django 5.2.6 on 2025-09-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_decription_testimonial_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Testimonials',
        ),
    ]
