# Generated by Django 5.2.6 on 2025-09-20 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_promoter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promoter',
            new_name='Promoters',
        ),
    ]
