# Generated by Django 5.2.6 on 2025-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(default='abcd', upload_to='testimonials/'),
            preserve_default=False,
        ),
    ]
