# Generated by Django 5.2.6 on 2025-09-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_subscribe_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='email',
        ),
    ]
