# Generated by Django 5.2.6 on 2025-09-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_subscribe_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(default='fuck@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
