# Generated by Django 5.2.6 on 2025-09-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='icon',
            field=models.FileField(upload_to='features/icon'),
        ),
        migrations.AlterField(
            model_name='features',
            name='testimonial_logo',
            field=models.FileField(upload_to='features/logo'),
        ),
    ]
