# Generated by Django 5.2.6 on 2025-09-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_reviews_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='midfeatures',
            name='link',
            field=models.CharField(default='#', max_length=256),
        ),
        migrations.AlterField(
            model_name='blog',
            name='link',
            field=models.CharField(default='#', max_length=256),
        ),
        migrations.AlterField(
            model_name='midfeatures',
            name='image',
            field=models.FileField(upload_to='midfeatures/image'),
        ),
    ]
