# Generated by Django 5.2.6 on 2025-09-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_midfeatures_link_alter_blog_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='products',
            name='hero_image',
            field=models.ImageField(default='', upload_to='products/hero_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='products',
            table='web_products',
        ),
    ]
