# Generated by Django 5.2.6 on 2025-09-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_products_options_products_hero_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='main_title',
        ),
    ]
