# Generated by Django 5.2.6 on 2025-09-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_rename_name_products_main_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='main_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
